[package]
name = "libqaul"
version = "2.0.0-beta.5"
authors = ["qaul.net community <contact@qaul.net>"]
edition = "2021"
license = "AGPL"

[lib]
name = "libqaul"
crate-type = ["cdylib", "staticlib", "rlib"]

[features]
default = []

[dependencies]
libp2p = { version = "0.48.0" }
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.15"
serde = {version = "=1.0", features = ["derive"] }
serde_json = "=1.0"
once_cell = "1.9"
log = "0.4"
pretty_env_logger = "0.4"
simplelog = "0.12.0"
multi_log = "0.1.2"
filetime = "0.2"
bincode = "1.3"
config = "0.13.2"
lazy_static = "1.4"
toml = "0.5"
base64 = "0.13"
state = "0.5"
humantime = "2.1"
tracing = "0.1.30"
void = "1.0"
wasm-timer = "0.2"
rand = "0.8"
prost = "0.11.0"
libc = "0.2"
crossbeam-channel = "0.5"
bs58 = "0.4"
futures-ticker = "0.0.2"
jni = "0.19"
serde_yaml = "0.9.9"
sled = "0.34.7"
sled-extensions = { version = "0.2", features = ["bincode"] }
uuid = { version = "1.1.2", features = ["v4"] }
ed25519-dalek = "1.0.1"
x25519-dalek = "1.2.0"
curve25519-dalek = "3.2.0"
sha2 = "0.10.2"
noise-protocol = { git = "https://github.com/MathJud/noise-rust.git", branch = "libp2p-45" }
noise-rust-crypto = { git = "https://github.com/MathJud/noise-rust.git", branch = "libp2p-45", features = ["use-x25519", "use-chacha20poly1305", "use-sha2"] }
crc = "^3.0.0"
fs_extra="1.2.0"

# only for desktop platforms: Linux, Mac, Windows
directories = "4.0"

# internal references
qaul_info = { path = "../libp2p_modules/qaul_info" }
qaul_messaging = { path = "../libp2p_modules/qaul_messaging" }

[build-dependencies]
prost-build = "0.11.1"


# special setting for android
[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"
